# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ee1e308cce75b2690f5ffaf5fef9da376aeb4bb6ae076ab5b39b4abec034ee6c0e4495539d84d39c7345b086cd66e8013020309153140f32c1fca6e1d6f77e

test:
  secret_key_base: 8c00142f82c073f76673bb60f790c7fae7b0f43331df6981fca5be67e61b158e5303513fd279a20a8568ad748f069fced421056dc3022635f49611e0b3312ff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
